# The name of your plugin as displayed in the Plugins Catalog web UI.
displayName: keycloakopenid

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/Gwojda/keycloakopenid

# A brief description of what your plugin is doing.
summary: This plugin for Traefik allows it to authenticate requests against Keycloak. It utilizes the Keycloak's client credentials flow to retrieve an access token, which is then set as a bearer token in the Authorization cookie and as a plain token in a custom named cookie of the incoming requests. Optionally sets the Bearer token in the Authorization header. The plugin communicates with Keycloak using the OpenID Connect protocol.

# Medias associated to the plugin (optional)
iconPath: foo/icon.png
bannerPath: foo/banner.png

# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  KeycloakURL: "my-keycloak-url.com"
  ClientID: "<CLIENT_ID"
  ClientSecret: "<CLIENT_SECRET"
  KeycloakRealm: "<REALM"
  Scope: "openid"
  TokenCookieName: "AUTH_TOKEN"
  UseAuthHeader: false
